title: "Gradiant Open5gs Operator"
description: "Deploy and manage Open5GS on Kubernetes with the Open5GS Operator"
theme: jekyll-theme-slate
baseurl: "/open5gs-go-operator-1"
relative_links:
  enabled: true
  collections: true
highlighter: rouge
markdown: kramdown
