apiVersion: open5gs.org/v1alpha1
kind: Subscriber
metadata:
  name: test-user-1
  namespace: open5gs
spec:
  # Identificación del suscriptor
  imsi: "208930000000001"
  plmnID: "20893"
  
  # Valores de autenticación (sensibles - en un entorno de producción, utiliza secrets)
  authenticationKey: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  
  # Opcional: usar OP en vez de OPC (descomenta si lo utilizas)
  # op: "11111111111111111111111111111111"
  
  # Configuración principal del suscriptor
  subscCat: 1  # Categoría del suscriptor
  accessRestrictionData: 32  # Restricciones de acceso
  
  # Algoritmos de seguridad permitidos
  encPermanent: 1  # 0: NEA0, 1: NEA1, 2: NEA2, 3: NEA3
  intProtection: 1  # 0: NIA0, 1: NIA1, 2: NIA2, 3: NIA3
  
  # Parámetros de QoS y velocidad
  ueAmbr:  # Aggregate Maximum Bit Rate para el UE
    uplink: "100 Mbps"
    downlink: "500 Mbps"
  
  # Configuración de Slices (Network Slicing)
  sliceConfigurations:
    # Slice principal para servicios estándar (eMBB)
    - sst: 1  # Slice Service Type (1: eMBB, 2: URLLC, 3: mMTC, 4: V2X)
      sd: "000001"  # Slice Differentiator (opcional)
      default: true  # Slice por defecto
      sessionAmbr:  # AMBR para esta slice
        uplink: "50 Mbps"
        downlink: "250 Mbps"
      dnn: "internet"  # Data Network Name (APN)
# Configuración de QoS para esta slice/DNN
      qosFlows:
        - qfi: 1  # QoS Flow Identifier
          priority: 10
          preEmptionCapability: false
          preEmptionVulnerability: false
          qosProfile:
            5qi: 9  # 5G QoS Identifier para QoS flow
            gbrUL: "0"  # Guaranteed Bit Rate Uplink
            gbrDL: "0"  # Guaranteed Bit Rate Downlink
            maxPacketLossRateUL: 0
            maxPacketLossRateDL: 0
    
    # Slice adicional para aplicaciones críticas (URLLC)
    - sst: 2  # URLLC
      sd: "000001"
      default: false
      sessionAmbr:
        uplink: "10 Mbps"
        downlink: "20 Mbps"
      dnn: "ims"  # Para servicios IMS/VoNR
  
  # Configuración estática de IP (opcional)
  staticIpAddress:
    enabled: false
    # Descomenta para asignar IP estática
    # ipv4: "10.45.0.100"
    # ipv6: "2001:db8::100"
  
  # Suscripción a servicios
  services:
    smsOverNas: true  # Habilitar SMS sobre NAS
    voiceService: true  # Habilitar servicio de voz
  
  # Referencia al despliegue de Open5GS
  deploymentRef:
    name: open5gs-demo
    namespace: open5gs
  
  # Etiquetas para organización (opcional)
  labels:
    type: "test-user"
    department: "engineering"
    location: "datacenter-1"